development:
  adapter: postgresql
  encoding: unicode
  database: demoday_development
  pool: 5
  username: 
  password:  
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  database: demoday_test
  pool: 5
  username: 
  password:  
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: demoday_production
  pool: 5
  username: demodaybuddy
  password:
